### ISSUE TITLE
e.message puede ser cualquier cosa

### ISSUE THREAD

**Issue by maurociancio** [jmoren/convivir-api#1]
https://github.com/jmoren/convivir-api/blob/bbbac740f19064db8cdb3cd4a013cf0371f292f4/grails-app/controllers/convivit/api/InvitationController.groovy#L50

no me copa mucho catchear exception, es demasiado amplio, incluso puede ser "no hay base excepcion"
catchearia los casos necesarios y usaria un mensaje hardcodiado en el controller o en messages.properties

el msg de la excepcion es para el programador, no para el usuario

**Comment by jmoren** [comment]
Estoy mandando mensajes a través de exceptions ahora. Cree unas custom, para al menos saber cuál se lanzó. Me faltó meterme un poco más con groovy y grails para usar errores del orm, o implementarlos mejor en la aplicación.
